CREATE TABLE STATION (
    ID int,
    CITY VARCHAR(21),
    STATE VARCHAr(2),
    LAT_N int,
    LONG_W int
);

INSERT INTO STATION (ID, CITY, STATE, LAT_N, LONG_W) VALUES (1, 'New York', 'NY', 40.7128, -74.0060);
INSERT INTO STATION (ID, CITY, STATE, LAT_N, LONG_W) VALUES (2, 'Los Angeles', 'CA', 34.0522, -118.2437);
INSERT INTO STATION (ID, CITY, STATE, LAT_N, LONG_W) VALUES (3, 'Chicago', 'IL', 41.8781, -87.6298);
INSERT INTO STATION (ID, CITY, STATE, LAT_N, LONG_W) VALUES (4, 'Houston', 'TX', 29.7604, -95.3698);
INSERT INTO STATION (ID, CITY, STATE, LAT_N, LONG_W) VALUES (5, 'Phoenix', 'AZ', 33.4484, -112.0740);


SELECT ROUND(
    ABS(MAX_LAT_N - MIN_LAT_N) + ABS(MAX_LONG_W - MIN_LONG_W), 
    4) AS manhattan_distance
FROM (
    SELECT 
        (SELECT MIN(LAT_N) FROM STATION) AS MIN_LAT_N,
        (SELECT MIN(LONG_W) FROM STATION) AS MIN_LONG_W,
        (SELECT MAX(LAT_N) FROM STATION) AS MAX_LAT_N,
        (SELECT MAX(LONG_W) FROM STATION) AS MAX_LONG_W
) AS bounds;




